server:
  port: 10001
  
spring:
  application:
    name: app-one
  datasource:
    url: jdbc:h2:mem:hr?useUnicode=yes&characterEncoding=UTF-8;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true   
      path : /h2-database
  jpa:
    generate-ddl: true
    show-sql: true 
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
       dialect : org.hibernate.dialect.H2Dialect       

       
       
      