server:
  port: 10001
  servlet:
    context-path: /app-two-api/
#########################################################       
spring:
  application:
    name: app-two-services
  profiles:
    active: dev  
  datasource:
    url: jdbc:h2:mem:hr;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:scripts/load.sql';
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-database
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#########################################################        
eureka:
  client:
    service-url:
      defaultZone: http://10.6.221.129:10003/eureka
  instance:
    instance-id : ${spring.application.name}:${spring.profiles.active}:${server.port} 
    lease-renewal-interval-in-seconds: 5
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health   
######################################################### 
app-one-services:
  ribbon:
    listOfServers: localhost:10000, localhost:10005
#########################################################         
info:
  application:
    name : ${spring.application.name}         